import type { Product } from "@/types/content";

export const products: Product[] = [
  {
    id: "alzdetect",
    slug: "alzdetect",
    category: "Healthcare AI",
    title: "AlzDetect",
    brandLabel: "A RIMANSTECH PRODUCT",
    headline: "AI-assisted brain MRI analysis with explainability built in.",
    description:
      "An AI-powered brain MRI analysis platform exploring Alzheimer's disease stage classification using Vision Transformers and explainable AI.",
    cta: { label: "Explore AlzDetect", href: "/products/alzdetect" },
    externalUrl: "https://www.alzdetect.live/",
    image: "/images/products/master_alz_analysis.png",
    imageAlt: "AlzDetect brain MRI analysis interface with classification results",
    imageFit: "cover",
    imageBg: "obsidian",
  },
  {
    id: "voicedress",
    slug: "voicedress",
    category: "AI Fashion Technology",
    title: "VoiceDress",
    brandLabel: "A RIMANSTECH PRODUCT",
    headline: "Your wardrobe, intelligently styled.",
    description:
      "VoiceDress is an AI-powered fashion platform that helps users discover outfit combinations from their own wardrobe based on the occasion, context and personal style.",
    cta: { label: "Explore VoiceDress", href: "/products/voicedress" },
    externalUrl: "https://www.voicedress.com/",
    image: "/images/products/voicedress-home.png",
    imageAlt: "VoiceDress — AI fashion styling platform demo",
    video: "/images/products/20260811-1945-02.5206643.mp4",
    imageFit: "cover",
    imageBg: "obsidian",
    aspect: "video",
  },
  {
    id: "young-ai-explorers",
    slug: "young-ai-explorers",
    category: "AI Education",
    title: "Young AI Explorers",
    brandLabel: "A RIMANSTECH PRODUCT",
    headline: "Helping the next generation understand artificial intelligence.",
    description:
      "An AI education initiative designed to make artificial intelligence understandable, practical and engaging for younger learners — spanning a digital platform, published book and STEM outreach.",
    cta: { label: "Explore Young AI Explorers", href: "/products/young-ai-explorers" },
    externalUrl: "https://www.youngaiexplorers.net/",
    image: "/images/products/young-ai-explorers-book.png",
    imageAlt: "Young AI Explorers book cover",
    imageFit: "cover",
    imageBg: "obsidian",
  },
  {
    id: "ai-quest",
    slug: "ai-quest",
    category: "Interactive AI Learning",
    title: "AI Quest",
    brandLabel: "A RIMANSTECH PRODUCT",
    headline: "Build. Train. Deploy. Play.",
    description:
      "AI Quest transforms concepts from the artificial intelligence development lifecycle into an interactive strategy experience — available as a physical card game and digital edition.",
    cta: { label: "Discover AI Quest", href: "/products/ai-quest" },
    externalUrl: "https://www.aiquestgame.com/",
    image: "/images/products/premium_game_box.png",
    imageAlt: "AI Quest premium game box",
    video: "/images/products/ai-quest-demo.mp4",
    imageFit: "cover",
  },
];
